import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./Style/product.css";
import "./Style/cart.css";
import "./Style/profile.css";
import "./Style/style.css";
 
 
 
import Script from "next/script";
import Footer from "./component/layout/Footer";
import Header from "./component/layout/Header";
import "./Style/style.css"
import 'bootstrap/dist/css/bootstrap.min.css';
import { CartProvider } from "./context/cartContext";
import SessionProviderWrapper from "./commponent/auth/SessionProviderWrapper";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en" >
  <head>
      

      <link rel="stylesheet" href="/plugins/owlcarousel/assets/owl.carousel.min.css"/>
      <link rel="stylesheet" href="/plugins/owlcarousel/assets/owl.theme.default.min.css"/>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/owl.carousel@2.3.4/dist/owl.carousel.min.js"></script>





<link rel="stylesheet" href="/fontawesome/css/all.min.css"/>

 
    <Script src="/js/jQuery-3.5.1.min.js" strategy="beforeInteractive"/>
    <Script src="/js/popper.js" strategy="beforeInteractive"/>  
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     
      <SessionProviderWrapper>
        <CartProvider>
          <Header />
          {children}
          <Footer />
        </CartProvider>
      </SessionProviderWrapper>
   
        <Script src="/plugins/owlcarousel/owl.carousel.min.js" strategy="afterInteractive"/>  
         <Script src="/js/main.js " strategy="lazyOnload"/>  
  
      </body>
    </html>
  );
}
